export type PreviewListing = {
  rank: number;
  handle: string;
  name: string;
  bio: string;
  platform: "youtube" | "instagram" | "tiktok" | "twitch" | "x" | "substack";
  categorySlug: string;
  bid: number;
  clicks: number;
  followers: string;
  ago: string;
  verified: boolean;
  initials: string;
  tint: string;
};

export const PREVIEW_LISTINGS: PreviewListing[] = [
  {
    rank: 1,
    handle: "maya.lifts",
    name: "Maya Lifts",
    bio: "Strength, mobility, and the 5am club. Programs for busy people who still want to get strong.",
    platform: "youtube",
    categorySlug: "fitness",
    bid: 847,
    clicks: 12840,
    followers: "412K",
    ago: "2d ago",
    verified: true,
    initials: "ML",
    tint: "#E55A2B",
  },
  {
    rank: 2,
    handle: "nightshift.dev",
    name: "Nightshift",
    bio: "Shipping tiny tools in public. AI explainers without the hype cycle.",
    platform: "youtube",
    categorySlug: "tech",
    bid: 612,
    clicks: 9102,
    followers: "188K",
    ago: "5h ago",
    verified: true,
    initials: "NS",
    tint: "#2F6B8F",
  },
  {
    rank: 3,
    handle: "lofi.lena",
    name: "Lofi Lena",
    bio: "Bedroom beats and late-night study radio. New mix every Sunday.",
    platform: "instagram",
    categorySlug: "music",
    bid: 480,
    clicks: 6401,
    followers: "96K",
    ago: "1d ago",
    verified: true,
    initials: "LL",
    tint: "#8A4E8C",
  },
  {
    rank: 4,
    handle: "kitchen.kiran",
    name: "Kiran Eats",
    bio: "Weeknight Indian food that actually fits in 25 minutes.",
    platform: "tiktok",
    categorySlug: "food",
    bid: 220,
    clicks: 4300,
    followers: "1.1M",
    ago: "3h ago",
    verified: false,
    initials: "KE",
    tint: "#C45C26",
  },
  {
    rank: 5,
    handle: "aria.reads",
    name: "Aria Reads",
    bio: "Longform essays on work, money, and making things. Substack on Sundays.",
    platform: "substack",
    categorySlug: "newsletters",
    bid: 175,
    clicks: 2104,
    followers: "54K",
    ago: "8h ago",
    verified: true,
    initials: "AR",
    tint: "#3F6B4A",
  },
  {
    rank: 6,
    handle: "clip.house",
    name: "Clip House",
    bio: "Faceless clips, tested hooks, no face, no voice — just retention.",
    platform: "youtube",
    categorySlug: "faceless",
    bid: 140,
    clicks: 3888,
    followers: "220K",
    ago: "12h ago",
    verified: false,
    initials: "CH",
    tint: "#4A5568",
  },
  {
    rank: 7,
    handle: "jay.on.tilt",
    name: "Jay on Tilt",
    bio: "Ranked grind, VOD review, and the occasional rage-quit apology.",
    platform: "twitch",
    categorySlug: "gaming",
    bid: 95,
    clicks: 1760,
    followers: "31K",
    ago: "4h ago",
    verified: true,
    initials: "JT",
    tint: "#6B3FA0",
  },
  {
    rank: 8,
    handle: "ruhi.does.money",
    name: "Ruhi Does Money",
    bio: "Personal finance for first-gen earners. No guru voice.",
    platform: "x",
    categorySlug: "finance",
    bid: 64,
    clicks: 980,
    followers: "78K",
    ago: "6h ago",
    verified: false,
    initials: "RD",
    tint: "#2F7D5A",
  },
  {
    rank: 9,
    handle: "the.dry.run",
    name: "The Dry Run",
    bio: "Comedy sketches about being online too much. That's the bit.",
    platform: "tiktok",
    categorySlug: "comedy",
    bid: 41,
    clicks: 2540,
    followers: "640K",
    ago: "20m ago",
    verified: true,
    initials: "DR",
    tint: "#C43D3D",
  },
  {
    rank: 10,
    handle: "studio.nori",
    name: "Studio Nori",
    bio: "Makeup that survives humidity. Honest reviews, no PR-speak.",
    platform: "instagram",
    categorySlug: "beauty",
    bid: 28,
    clicks: 1120,
    followers: "19K",
    ago: "1h ago",
    verified: false,
    initials: "SN",
    tint: "#B76E79",
  },
];

export const PREVIEW_ACTIVITY = [
  { handle: "the.dry.run", rank: 9, bid: 41, ago: "20m ago" },
  { handle: "studio.nori", rank: 10, bid: 28, ago: "1h ago" },
  { handle: "kitchen.kiran", rank: 4, bid: 220, ago: "3h ago" },
  { handle: "jay.on.tilt", rank: 7, bid: 95, ago: "4h ago" },
  { handle: "nightshift.dev", rank: 2, bid: 612, ago: "5h ago" },
  { handle: "ruhi.does.money", rank: 8, bid: 64, ago: "6h ago" },
];
